apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mlflow-db
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # database healthy before MLflow starts
spec:
  instances: 1
  storage:
    size: 2Gi
